### ISSUE TITLE
Implement dependency graph viewer

### ISSUE THREAD

**Issue by fccoelho** [fccoelho/pypixplorer#7]
Use the ete3 library to generate the dependency trees, follwing the documentation [here](http://etetoolkit.org/docs/latest/tutorial/tutorial_trees.html#creating-trees-from-scratch):

**Comment by fccoelho** [comment]
@odanoburu, are you going to use [pipdeptree](https://pypi.python.org/pypi/pipdeptree/0.6.0)?

**Comment by fccoelho** [comment]
It may not be to cumbersome to actually download the package, check for a requirements.txt and the `install_requires` on setup.py for dependencies. If we cache the package info, we may not need to download many packages after a while. You can cache the dependency tree by pickling the graph. and keeping it in the repo for reuse.

**Comment by odanoburu** [comment]
@fccoelho I was thinking of using either pipdeptree or the 'pip show' command. if there's no problem with using several dependencies on our own projects, I'd rather use pipdeptree.

> It may not be to cumbersome to actually download the package, check for a requirements.txt and the install_requires on setup.py for dependencies.

it might be, because I checked the packages I have installed and most of them do not have the same standard; some use the requirements.txt, some have a setup.py, but some have the info on other directories with other names...
